name: run-on-ubuntu
run-name: ${{ github.actor }} started the action 🚀
on:
  workflow_dispatch:
    inputs:
      subdomain:
        required: true
        type: string
        description: 'The sub-domain for geo-location'
      domain:
        required: true
        type: string
        description: 'The url against which test to be run'
      
jobs:
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.stdout }}
    steps:
      - name: Checkout & Logging input details
        id: step1
        uses: actions/checkout@v3

      - name: Install Postman CLI
        id: step2
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          echo "🤖 Verifying Postman CLI install.."

      - name: Verify Postman CLI install
        id: step3
        run: |
          echo "💯 Postman CLI installed."
          postman -v
          echo "Logging.."
          echo ${{ steps.step3.outputs.stdout }}
          

      - name: Postman CLI Login
        id: step4
        if: ${{ (steps.step3.outputs.stdout =~ ^[0-9]+\.[0-9]+\.[0-9]+$) }}
        run: |
          postman login --with-api-key PMAK-635adf435c78e7380cbf9ab3-a9d00a70784f08415cb7e4870bf0caff3c
        
      - name: Run Test Collections
        id: step5
        env:
          DOMAIN: ${{ inputs.domain }}
          SUBDOMAIN: ${{ inputs.subdomain }}s
        run: |
            echo $DOMAIN
            echo $SUBDOMAIN
            postman collection run postman_collection.json -g postman_globals.json -e env/QA/postman_environment.json
      - run: echo "✔️ All tests were run with status ${{ job.status }}."