name: Testing reusable workflow
run-name: ${{ github.actor }} started the action 🚀
on:
  workflow_dispatch:
    inputs:
      subdomain:
        required: true
        type: string
        description: 'The sub-domain for geo-location'
      domain:
        required: true
        type: string
        description: 'The url against which test to be run'
    secrets:
      postman_api_key:
        required: true   
        description: 'The token is pulled from GitHub repository secrets'

jobs:     
  run-tests:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.stdout }}
    steps:
      - name: Checkout & Logging input details
        id: step1
        uses: actions/checkout@v3

      - name: Install Postman CLI
        id: step2
        uses: far11ven/postman-cli-with-github-actions/.github/workflows/reusable-workflow.yml@main
        with:
            postman-api-key: ${{ secrets.postman_api_key }}

      - name: Run Test Collections
        id: step3
        env:
          DOMAIN: ${{ inputs.domain }}
          SUBDOMAIN: ${{ inputs.subdomain }}s
        run: |
            echo $DOMAIN
            echo $SUBDOMAIN
            postman collection run postman_collection.json -g postman_globals.json -e env/QA/postman_environment.json

      - run: echo "✔️ All tests were run with status ${{ job.status }}."